# .travis.yml
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - node_modules
before_script:
  - npm install -g npm@latest
  - npm install -g yarn
  - npm install -g expo-cli
script:
  - yarn
jobs:
  include:
    - stage: deploy website
      script:
        - yarn
        - expo build:web
      deploy:
        provider: netlify
        site: uniguesser.netlify.app
        auth: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDoZUOBioQ4pOhUgL47NyVQ0NVd6wCTBqNmzM2yKcZSWixsmAzkYJWQe3SBfiLfWpcJS6dAgs4E3YeVDggIgylUR5JHGXij9d3YrkA4T/DAA9UzwYLCeF89/OvUqja8Ov5G+eeRTscGGPOhzyRq/ho18TN01UTK4SUd/WY8MHDE3OJUj1hjN/tdXhPSOtmGYas8b8FndpWCQxX7bf/6w0LCPl2We6Gt48PLRlNZliZ60VKW2yAhOE25fhatRRxNlsapNtVqS/YLqyhsiuPFZH2zXtdx8HmhGYfO+JjdaE1xbWeEcSTxylqA2TdAKioWXb0SzufL2fQ4a0BTeR/4Vr3uihkT8KmtjHe/w8tcWF2+1LbA0GZBceWkLDIpsm4kbYI8ZeBksmO8NMAfeArqOzBhlUC93qC3XGA3VwpMn32pNtsanXjdWl2eMKhtl8LQf3Be7VKdv60SoPo9731VGA0RrX+hwxIc7F9Lvo36F6bgSZUkZhYCWJHO3510SMNQwjXoxZ5wKjSls1tlf1trsYtEjaHNZyItYptbDJAyCgK2EHYVgTGg/0g+AInrXgnWIjcVQg+R3xipkPdZaLxRjQanzSWUQZC3sAlnVSB9yUQ2F4eSVjsG4YC+wELCSR2XU07aFo58zuzANEIX45EkjyIyT1uQpGxUcbA0fluxe+IGOw==
        dir: "web-build"
        prod: true
        edge: true
        on:
          branch: master